# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52e1642f57f76a77094aa8f8104f84a6d55a0514f5e6d12589a058cebd876ec2cdfa2464f4c39a90aa0c73109c27638730d628e70426ac7dc07a657f4bf7f19e

test:
  secret_key_base: 372346d7d168f6ab65a5acb710097da9681079e00350facf766233d4ba33176c0b2ba28169a1f271048670bd766b5e88a77a2e6f27e7953812264e5eea7baf8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
